/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) fk_panda_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};

/* fkpanda_hand:(i0[7])->(o0[4x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a5, a6, a7, a8, a9;
  a0=7.0710678118686454e-01;
  a1=arg[0]? arg[0][0] : 0;
  a2=cos(a1);
  a3=arg[0]? arg[0][1] : 0;
  a4=cos(a3);
  a5=(a2*a4);
  a1=sin(a1);
  a6=4.8965888601467475e-12;
  a3=sin(a3);
  a7=(a6*a3);
  a8=(a1*a7);
  a5=(a5-a8);
  a8=arg[0]? arg[0][2] : 0;
  a9=cos(a8);
  a10=(a5*a9);
  a11=(a2*a3);
  a12=(a6*a4);
  a13=(a1*a12);
  a11=(a11+a13);
  a8=sin(a8);
  a13=(a6*a8);
  a14=(a11*a13);
  a10=(a10-a14);
  a14=(a1*a8);
  a10=(a10-a14);
  a14=arg[0]? arg[0][3] : 0;
  a15=cos(a14);
  a16=(a10*a15);
  a5=(a5*a8);
  a17=(a6*a9);
  a18=(a11*a17);
  a5=(a5+a18);
  a18=(a1*a9);
  a5=(a5+a18);
  a14=sin(a14);
  a18=(a6*a14);
  a19=(a5*a18);
  a16=(a16-a19);
  a19=(a6*a1);
  a19=(a11-a19);
  a20=(a19*a14);
  a16=(a16+a20);
  a20=arg[0]? arg[0][4] : 0;
  a21=cos(a20);
  a22=(a16*a21);
  a23=(a19*a15);
  a24=(a10*a14);
  a25=(a6*a15);
  a26=(a5*a25);
  a24=(a24+a26);
  a23=(a23-a24);
  a20=sin(a20);
  a24=(a6*a20);
  a26=(a23*a24);
  a22=(a22+a26);
  a19=(a6*a19);
  a5=(a5+a19);
  a19=(a5*a20);
  a22=(a22-a19);
  a19=arg[0]? arg[0][5] : 0;
  a26=cos(a19);
  a27=(a22*a26);
  a28=(a6*a21);
  a29=(a23*a28);
  a30=(a16*a20);
  a29=(a29-a30);
  a30=(a5*a21);
  a29=(a29-a30);
  a19=sin(a19);
  a30=(a6*a19);
  a31=(a29*a30);
  a27=(a27+a31);
  a5=(a6*a5);
  a5=(a23+a5);
  a31=(a5*a19);
  a27=(a27+a31);
  a31=arg[0]? arg[0][6] : 0;
  a32=cos(a31);
  a33=(a27*a32);
  a34=(a6*a26);
  a35=(a29*a34);
  a22=(a22*a19);
  a35=(a35-a22);
  a22=(a5*a26);
  a35=(a35+a22);
  a31=sin(a31);
  a22=(a6*a31);
  a36=(a35*a22);
  a33=(a33+a36);
  a5=(a6*a5);
  a5=(a5-a29);
  a29=(a5*a31);
  a33=(a33+a29);
  a29=(a0*a33);
  a36=-7.0710678118623049e-01;
  a37=(a6*a32);
  a38=(a35*a37);
  a39=(a27*a31);
  a38=(a38-a39);
  a39=(a5*a32);
  a38=(a38+a39);
  a39=(a36*a38);
  a29=(a29+a39);
  if (res[0]!=0) res[0][0]=a29;
  a29=(a1*a4);
  a7=(a2*a7);
  a29=(a29+a7);
  a7=(a29*a9);
  a12=(a2*a12);
  a1=(a1*a3);
  a12=(a12-a1);
  a1=(a12*a13);
  a7=(a7+a1);
  a1=(a2*a8);
  a7=(a7+a1);
  a1=(a7*a15);
  a39=(a12*a17);
  a29=(a29*a8);
  a39=(a39-a29);
  a29=(a2*a9);
  a39=(a39+a29);
  a29=(a39*a18);
  a1=(a1+a29);
  a2=(a6*a2);
  a2=(a2-a12);
  a29=(a2*a14);
  a1=(a1+a29);
  a29=(a1*a21);
  a40=(a39*a25);
  a41=(a7*a14);
  a40=(a40-a41);
  a41=(a2*a15);
  a40=(a40+a41);
  a41=(a40*a24);
  a29=(a29+a41);
  a2=(a6*a2);
  a2=(a2-a39);
  a39=(a2*a20);
  a29=(a29-a39);
  a39=(a29*a26);
  a41=(a40*a28);
  a42=(a1*a20);
  a41=(a41-a42);
  a42=(a2*a21);
  a41=(a41-a42);
  a42=(a41*a30);
  a39=(a39+a42);
  a2=(a6*a2);
  a2=(a40+a2);
  a42=(a2*a19);
  a39=(a39+a42);
  a42=(a39*a32);
  a43=(a41*a34);
  a29=(a29*a19);
  a43=(a43-a29);
  a29=(a2*a26);
  a43=(a43+a29);
  a29=(a43*a22);
  a42=(a42+a29);
  a2=(a6*a2);
  a2=(a2-a41);
  a41=(a2*a31);
  a42=(a42+a41);
  a41=(a0*a42);
  a29=(a43*a37);
  a44=(a39*a31);
  a29=(a29-a44);
  a44=(a2*a32);
  a29=(a29+a44);
  a44=(a36*a29);
  a41=(a41+a44);
  if (res[0]!=0) res[0][1]=a41;
  a41=(a6*a8);
  a44=(a3*a9);
  a13=(a4*a13);
  a44=(a44+a13);
  a41=(a41-a44);
  a44=(a41*a15);
  a3=(a3*a8);
  a17=(a4*a17);
  a3=(a3-a17);
  a9=(a6*a9);
  a3=(a3+a9);
  a18=(a3*a18);
  a44=(a44+a18);
  a18=2.3976582465313225e-23;
  a18=(a4+a18);
  a9=(a18*a14);
  a44=(a44+a9);
  a9=(a44*a21);
  a25=(a3*a25);
  a14=(a41*a14);
  a25=(a25-a14);
  a15=(a18*a15);
  a25=(a25+a15);
  a24=(a25*a24);
  a9=(a9+a24);
  a18=(a6*a18);
  a18=(a18-a3);
  a3=(a18*a20);
  a9=(a9-a3);
  a3=(a9*a26);
  a28=(a25*a28);
  a20=(a44*a20);
  a28=(a28-a20);
  a21=(a18*a21);
  a28=(a28-a21);
  a30=(a28*a30);
  a3=(a3+a30);
  a18=(a6*a18);
  a18=(a25+a18);
  a30=(a18*a19);
  a3=(a3+a30);
  a30=(a3*a32);
  a34=(a28*a34);
  a9=(a9*a19);
  a34=(a34-a9);
  a26=(a18*a26);
  a34=(a34+a26);
  a22=(a34*a22);
  a30=(a30+a22);
  a18=(a6*a18);
  a18=(a18-a28);
  a28=(a18*a31);
  a30=(a30+a28);
  a28=(a0*a30);
  a37=(a34*a37);
  a31=(a3*a31);
  a37=(a37-a31);
  a32=(a18*a32);
  a37=(a37+a32);
  a36=(a36*a37);
  a28=(a28+a36);
  if (res[0]!=0) res[0][2]=a28;
  a28=0.;
  if (res[0]!=0) res[0][3]=a28;
  a36=7.0710678118623049e-01;
  a33=(a36*a33);
  a38=(a0*a38);
  a33=(a33+a38);
  if (res[0]!=0) res[0][4]=a33;
  a42=(a36*a42);
  a29=(a0*a29);
  a42=(a42+a29);
  if (res[0]!=0) res[0][5]=a42;
  a36=(a36*a30);
  a0=(a0*a37);
  a36=(a36+a0);
  if (res[0]!=0) res[0][6]=a36;
  if (res[0]!=0) res[0][7]=a28;
  a5=(a6*a5);
  a5=(a5-a35);
  if (res[0]!=0) res[0][8]=a5;
  a2=(a6*a2);
  a2=(a2-a43);
  if (res[0]!=0) res[0][9]=a2;
  a6=(a6*a18);
  a6=(a6-a34);
  if (res[0]!=0) res[0][10]=a6;
  if (res[0]!=0) res[0][11]=a28;
  a28=1.0700000000000000e-01;
  a5=(a28*a5);
  a34=8.7999999999999995e-02;
  a27=(a34*a27);
  a18=-8.2500000000000004e-02;
  a16=(a18*a16);
  a43=3.8400000000000001e-01;
  a23=(a43*a23);
  a16=(a16+a23);
  a23=8.2500000000000004e-02;
  a10=(a23*a10);
  a35=-3.1600000000000000e-01;
  a11=(a35*a11);
  a10=(a10-a11);
  a16=(a16+a10);
  a27=(a27+a16);
  a5=(a5+a27);
  if (res[0]!=0) res[0][12]=a5;
  a2=(a28*a2);
  a39=(a34*a39);
  a1=(a18*a1);
  a40=(a43*a40);
  a1=(a1+a40);
  a7=(a23*a7);
  a12=(a35*a12);
  a7=(a7+a12);
  a1=(a1+a7);
  a39=(a39+a1);
  a2=(a2+a39);
  if (res[0]!=0) res[0][13]=a2;
  a28=(a28*a6);
  a34=(a34*a3);
  a18=(a18*a44);
  a43=(a43*a25);
  a18=(a18+a43);
  a23=(a23*a41);
  a41=3.3300000000000002e-01;
  a35=(a35*a4);
  a41=(a41-a35);
  a23=(a23+a41);
  a18=(a18+a23);
  a34=(a34+a18);
  a28=(a28+a34);
  if (res[0]!=0) res[0][14]=a28;
  a28=1.;
  if (res[0]!=0) res[0][15]=a28;
  return 0;
}

CASADI_SYMBOL_EXPORT int fkpanda_hand(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int fkpanda_hand_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int fkpanda_hand_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fkpanda_hand_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int fkpanda_hand_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fkpanda_hand_release(int mem) {
}

CASADI_SYMBOL_EXPORT void fkpanda_hand_incref(void) {
}

CASADI_SYMBOL_EXPORT void fkpanda_hand_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int fkpanda_hand_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int fkpanda_hand_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real fkpanda_hand_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fkpanda_hand_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fkpanda_hand_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fkpanda_hand_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fkpanda_hand_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int fkpanda_hand_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int fkpanda_hand_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
