/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) fk_panda_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};

/* fkpanda_hand_tcp:(i0[7])->(o0[4x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97;
  a0=7.0710678118654757e-01;
  a1=arg[0]? arg[0][0] : 0;
  a2=cos(a1);
  a3=-5.6145195983694997e-16;
  a1=sin(a1);
  a4=(a3*a1);
  a4=(a2+a4);
  a5=9.9999954170564220e-01;
  a6=arg[0]? arg[0][1] : 0;
  a7=cos(a6);
  a8=(a5*a7);
  a9=-9.5738542162738583e-04;
  a6=sin(a6);
  a10=(a9*a6);
  a8=(a8+a10);
  a10=(a4*a8);
  a3=(a3*a2);
  a3=(a3-a1);
  a11=3.8232556512900575e-10;
  a12=(a11*a7);
  a13=-1.3453236470433816e-03;
  a14=(a13*a6);
  a12=(a12+a14);
  a14=(a3*a12);
  a10=(a10+a14);
  a14=-6.3328469940015534e-16;
  a15=-9.5738628852680007e-04;
  a16=(a15*a7);
  a17=-9.9999863675779033e-01;
  a18=(a17*a6);
  a16=(a16+a18);
  a18=(a14*a16);
  a10=(a10+a18);
  a18=9.9999924824581299e-01;
  a19=arg[0]? arg[0][2] : 0;
  a20=cos(a19);
  a21=(a18*a20);
  a22=-6.5399258580682237e-04;
  a19=sin(a19);
  a23=(a22*a19);
  a21=(a21+a23);
  a23=(a10*a21);
  a9=(a9*a7);
  a5=(a5*a6);
  a9=(a9-a5);
  a5=(a4*a9);
  a13=(a13*a7);
  a11=(a11*a6);
  a13=(a13-a11);
  a11=(a3*a13);
  a5=(a5+a11);
  a17=(a17*a7);
  a15=(a15*a6);
  a17=(a17-a15);
  a14=(a14*a17);
  a5=(a5+a14);
  a14=1.0361366514215311e-03;
  a15=(a14*a20);
  a6=-1.6371700745771278e-03;
  a7=(a6*a19);
  a15=(a15+a7);
  a7=(a5*a15);
  a23=(a23+a7);
  a7=-1.2883767383541285e-06;
  a11=(a7*a4);
  a24=9.9999909505173290e-01;
  a25=(a24*a3);
  a11=(a11+a25);
  a25=8.5197249072762098e-19;
  a11=(a11+a25);
  a25=6.5568944503676893e-04;
  a26=(a25*a20);
  a27=9.9999844598271481e-01;
  a28=(a27*a19);
  a26=(a26+a28);
  a28=(a11*a26);
  a23=(a23+a28);
  a28=9.9995021809807760e-01;
  a29=arg[0]? arg[0][3] : 0;
  a30=cos(a29);
  a31=(a28*a30);
  a32=9.9540068369970026e-03;
  a29=sin(a29);
  a33=(a32*a29);
  a31=(a31+a33);
  a33=(a23*a31);
  a22=(a22*a20);
  a18=(a18*a19);
  a22=(a22-a18);
  a18=(a10*a22);
  a6=(a6*a20);
  a14=(a14*a19);
  a6=(a6-a14);
  a14=(a5*a6);
  a18=(a18+a14);
  a27=(a27*a20);
  a25=(a25*a19);
  a27=(a27-a25);
  a25=(a11*a27);
  a18=(a18+a25);
  a25=7.0706569900143453e-04;
  a19=(a25*a30);
  a20=-1.4948847449833551e-03;
  a14=(a20*a29);
  a19=(a19+a14);
  a14=(a18*a19);
  a33=(a33+a14);
  a14=1.0372085163848953e-03;
  a34=(a14*a10);
  a35=-9.9999812304573177e-01;
  a36=(a35*a5);
  a34=(a34+a36);
  a36=-1.6364912181397568e-03;
  a37=(a36*a11);
  a34=(a34+a37);
  a37=-9.9529585402638159e-03;
  a38=(a37*a30);
  a39=9.9994934025053905e-01;
  a40=(a39*a29);
  a38=(a38+a40);
  a40=(a34*a38);
  a33=(a33+a40);
  a40=9.9993393914134043e-01;
  a41=arg[0]? arg[0][4] : 0;
  a42=cos(a41);
  a43=(a40*a42);
  a44=-5.7476515743761763e-03;
  a41=sin(a41);
  a45=(a44*a41);
  a43=(a43+a45);
  a45=(a33*a43);
  a32=(a32*a30);
  a28=(a28*a29);
  a32=(a32-a28);
  a28=(a23*a32);
  a20=(a20*a30);
  a25=(a25*a29);
  a20=(a20-a25);
  a25=(a18*a20);
  a28=(a28+a25);
  a39=(a39*a30);
  a37=(a37*a29);
  a39=(a39-a37);
  a37=(a34*a39);
  a28=(a28+a37);
  a37=-9.9529603585239747e-03;
  a29=(a37*a42);
  a30=2.0717355177715061e-04;
  a25=(a30*a41);
  a29=(a29+a25);
  a25=(a28*a29);
  a45=(a45+a25);
  a25=6.9215135334097855e-04;
  a46=(a25*a23);
  a47=-9.9999863268791356e-01;
  a48=(a47*a18);
  a46=(a46+a48);
  a48=-1.5018484635796615e-03;
  a49=(a48*a34);
  a46=(a46+a49);
  a49=-5.7494289615239880e-03;
  a50=(a49*a42);
  a51=-9.9998346065347454e-01;
  a52=(a51*a41);
  a50=(a50+a52);
  a52=(a46*a50);
  a45=(a45+a52);
  a52=9.9998363119856526e-01;
  a53=arg[0]? arg[0][5] : 0;
  a54=cos(a53);
  a55=(a52*a54);
  a56=5.6266201852465502e-04;
  a53=sin(a53);
  a57=(a56*a53);
  a55=(a55+a57);
  a57=(a45*a55);
  a44=(a44*a42);
  a40=(a40*a41);
  a44=(a44-a40);
  a40=(a33*a44);
  a30=(a30*a42);
  a37=(a37*a41);
  a30=(a30-a37);
  a37=(a28*a30);
  a40=(a40+a37);
  a51=(a51*a42);
  a49=(a49*a41);
  a51=(a51-a49);
  a49=(a46*a51);
  a40=(a40+a49);
  a49=5.6946070722528937e-03;
  a41=(a49*a54);
  a42=-1.2237627060604629e-03;
  a37=(a42*a53);
  a41=(a41+a37);
  a37=(a40*a41);
  a57=(a57+a37);
  a37=9.9539868726823012e-03;
  a58=(a37*a33);
  a59=9.9995044660184085e-01;
  a60=(a59*a28);
  a58=(a58+a60);
  a60=1.4995371744005469e-04;
  a61=(a60*a46);
  a58=(a58+a61);
  a61=-5.5568446471818763e-04;
  a62=(a61*a54);
  a63=9.9999909290773470e-01;
  a64=(a63*a53);
  a62=(a62+a64);
  a64=(a58*a62);
  a57=(a57+a64);
  a64=9.9999994795429736e-01;
  a65=arg[0]? arg[0][6] : 0;
  a66=cos(a65);
  a67=(a64*a66);
  a68=-1.7139802423393207e-09;
  a65=sin(a65);
  a69=(a68*a65);
  a67=(a67+a69);
  a69=(a57*a67);
  a56=(a56*a54);
  a52=(a52*a53);
  a56=(a56-a52);
  a52=(a45*a56);
  a42=(a42*a54);
  a49=(a49*a53);
  a42=(a42-a49);
  a49=(a40*a42);
  a52=(a52+a49);
  a63=(a63*a54);
  a61=(a61*a53);
  a63=(a63-a61);
  a61=(a58*a63);
  a52=(a52+a61);
  a61=-3.2263196397108046e-04;
  a53=(a61*a66);
  a54=4.1634135175003684e-04;
  a49=(a54*a65);
  a53=(a53+a49);
  a49=(a52*a53);
  a69=(a69+a49);
  a49=5.6939218807946059e-03;
  a70=(a49*a45);
  a71=-9.9998303678369060e-01;
  a72=(a71*a40);
  a70=(a70+a72);
  a72=-1.2269468136417029e-03;
  a73=(a72*a58);
  a70=(a70+a73);
  a73=1.3603901994113347e-07;
  a74=(a73*a66);
  a75=9.9999991332993565e-01;
  a76=(a75*a65);
  a74=(a74+a76);
  a76=(a70*a74);
  a69=(a69+a76);
  a76=(a0*a69);
  a77=-7.0710678118654746e-01;
  a68=(a68*a66);
  a64=(a64*a65);
  a68=(a68-a64);
  a64=(a57*a68);
  a54=(a54*a66);
  a61=(a61*a65);
  a54=(a54-a61);
  a61=(a52*a54);
  a64=(a64+a61);
  a75=(a75*a66);
  a73=(a73*a65);
  a75=(a75-a73);
  a73=(a70*a75);
  a64=(a64+a73);
  a73=(a77*a64);
  a76=(a76+a73);
  if (res[0]!=0) res[0][0]=a76;
  a73=5.6145195983694987e-16;
  a65=(a73*a2);
  a65=(a65+a1);
  a66=(a65*a8);
  a73=(a73*a1);
  a73=(a2-a73);
  a61=(a73*a12);
  a66=(a66+a61);
  a61=-8.6899929445947751e-17;
  a78=(a61*a16);
  a66=(a66+a78);
  a78=(a66*a21);
  a79=(a65*a9);
  a80=(a73*a13);
  a79=(a79+a80);
  a61=(a61*a17);
  a79=(a79+a61);
  a61=(a79*a15);
  a78=(a78+a61);
  a61=(a7*a65);
  a80=(a24*a73);
  a61=(a61+a80);
  a80=1.1690847639970706e-19;
  a61=(a61+a80);
  a80=(a61*a26);
  a78=(a78+a80);
  a80=(a78*a31);
  a81=(a66*a22);
  a82=(a79*a6);
  a81=(a81+a82);
  a82=(a61*a27);
  a81=(a81+a82);
  a82=(a81*a19);
  a80=(a80+a82);
  a82=(a14*a66);
  a83=(a35*a79);
  a82=(a82+a83);
  a83=(a36*a61);
  a82=(a82+a83);
  a83=(a82*a38);
  a80=(a80+a83);
  a83=(a80*a43);
  a84=(a78*a32);
  a85=(a81*a20);
  a84=(a84+a85);
  a85=(a82*a39);
  a84=(a84+a85);
  a85=(a84*a29);
  a83=(a83+a85);
  a85=(a25*a78);
  a86=(a47*a81);
  a85=(a85+a86);
  a86=(a48*a82);
  a85=(a85+a86);
  a86=(a85*a50);
  a83=(a83+a86);
  a86=(a83*a55);
  a87=(a80*a44);
  a88=(a84*a30);
  a87=(a87+a88);
  a88=(a85*a51);
  a87=(a87+a88);
  a88=(a87*a41);
  a86=(a86+a88);
  a88=(a37*a80);
  a89=(a59*a84);
  a88=(a88+a89);
  a89=(a60*a85);
  a88=(a88+a89);
  a89=(a88*a62);
  a86=(a86+a89);
  a89=(a86*a67);
  a90=(a83*a56);
  a91=(a87*a42);
  a90=(a90+a91);
  a91=(a88*a63);
  a90=(a90+a91);
  a91=(a90*a53);
  a89=(a89+a91);
  a91=(a49*a83);
  a92=(a71*a87);
  a91=(a91+a92);
  a92=(a72*a88);
  a91=(a91+a92);
  a92=(a91*a74);
  a89=(a89+a92);
  a92=(a0*a89);
  a93=(a86*a68);
  a94=(a90*a54);
  a93=(a93+a94);
  a94=(a91*a75);
  a93=(a93+a94);
  a94=(a77*a93);
  a92=(a92+a94);
  if (res[0]!=0) res[0][1]=a92;
  a94=6.3328469940015534e-16;
  a95=(a94*a2);
  a96=8.6899929445947394e-17;
  a97=(a96*a1);
  a95=(a95+a97);
  a8=(a95*a8);
  a96=(a96*a2);
  a94=(a94*a1);
  a96=(a96-a94);
  a12=(a96*a12);
  a8=(a8+a12);
  a8=(a8+a16);
  a21=(a8*a21);
  a9=(a95*a9);
  a13=(a96*a13);
  a9=(a9+a13);
  a9=(a9+a17);
  a15=(a9*a15);
  a21=(a21+a15);
  a7=(a7*a95);
  a24=(a24*a96);
  a7=(a7+a24);
  a24=-1.3453230301231117e-03;
  a7=(a7+a24);
  a26=(a7*a26);
  a21=(a21+a26);
  a31=(a21*a31);
  a22=(a8*a22);
  a6=(a9*a6);
  a22=(a22+a6);
  a27=(a7*a27);
  a22=(a22+a27);
  a19=(a22*a19);
  a31=(a31+a19);
  a14=(a14*a8);
  a35=(a35*a9);
  a14=(a14+a35);
  a36=(a36*a7);
  a14=(a14+a36);
  a38=(a14*a38);
  a31=(a31+a38);
  a43=(a31*a43);
  a32=(a21*a32);
  a20=(a22*a20);
  a32=(a32+a20);
  a39=(a14*a39);
  a32=(a32+a39);
  a29=(a32*a29);
  a43=(a43+a29);
  a25=(a25*a21);
  a47=(a47*a22);
  a25=(a25+a47);
  a48=(a48*a14);
  a25=(a25+a48);
  a50=(a25*a50);
  a43=(a43+a50);
  a55=(a43*a55);
  a44=(a31*a44);
  a30=(a32*a30);
  a44=(a44+a30);
  a51=(a25*a51);
  a44=(a44+a51);
  a41=(a44*a41);
  a55=(a55+a41);
  a37=(a37*a31);
  a59=(a59*a32);
  a37=(a37+a59);
  a60=(a60*a25);
  a37=(a37+a60);
  a62=(a37*a62);
  a55=(a55+a62);
  a67=(a55*a67);
  a56=(a43*a56);
  a42=(a44*a42);
  a56=(a56+a42);
  a63=(a37*a63);
  a56=(a56+a63);
  a53=(a56*a53);
  a67=(a67+a53);
  a49=(a49*a43);
  a71=(a71*a44);
  a49=(a49+a71);
  a72=(a72*a37);
  a49=(a49+a72);
  a74=(a49*a74);
  a67=(a67+a74);
  a74=(a0*a67);
  a68=(a55*a68);
  a54=(a56*a54);
  a68=(a68+a54);
  a75=(a49*a75);
  a68=(a68+a75);
  a77=(a77*a68);
  a74=(a74+a77);
  if (res[0]!=0) res[0][2]=a74;
  a77=0.;
  if (res[0]!=0) res[0][3]=a77;
  a75=7.0710678118654746e-01;
  a69=(a75*a69);
  a64=(a0*a64);
  a69=(a69+a64);
  if (res[0]!=0) res[0][4]=a69;
  a89=(a75*a89);
  a93=(a0*a93);
  a89=(a89+a93);
  if (res[0]!=0) res[0][5]=a89;
  a75=(a75*a67);
  a0=(a0*a68);
  a75=(a75+a0);
  if (res[0]!=0) res[0][6]=a75;
  if (res[0]!=0) res[0][7]=a77;
  a0=-3.2263199264721685e-04;
  a68=(a0*a57);
  a67=-9.9999986128423768e-01;
  a93=(a67*a52);
  a68=(a68+a93);
  a93=4.1634132952827384e-04;
  a64=(a93*a70);
  a68=(a68+a64);
  if (res[0]!=0) res[0][8]=a68;
  a64=(a0*a86);
  a54=(a67*a90);
  a64=(a64+a54);
  a54=(a93*a91);
  a64=(a64+a54);
  if (res[0]!=0) res[0][9]=a64;
  a0=(a0*a55);
  a67=(a67*a56);
  a0=(a0+a67);
  a93=(a93*a49);
  a0=(a0+a93);
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a77;
  a77=3.6095072086067933e-04;
  a76=(a77*a76);
  a93=1.7059979976771745e-04;
  a69=(a93*a69);
  a76=(a76+a69);
  a69=1.3099237856829304e-01;
  a67=(a69*a68);
  a76=(a76+a67);
  a67=1.0700000000000000e-01;
  a68=(a67*a68);
  a54=9.0081181068136271e-02;
  a57=(a54*a57);
  a72=-2.5930422314298100e-03;
  a52=(a72*a52);
  a57=(a57+a52);
  a52=-2.9591128047994401e-04;
  a70=(a52*a70);
  a57=(a57+a70);
  a70=7.1273919490806960e-04;
  a45=(a70*a45);
  a71=3.0073005130449627e-04;
  a40=(a71*a40);
  a45=(a45+a40);
  a40=-5.9438914563187577e-04;
  a58=(a40*a58);
  a45=(a45+a58);
  a58=-7.7585738555283279e-02;
  a33=(a58*a33);
  a53=3.8334170655245070e-01;
  a28=(a53*a28);
  a33=(a33+a28);
  a28=6.5127903754357420e-04;
  a46=(a28*a46);
  a33=(a33+a46);
  a46=8.1664438995949828e-02;
  a23=(a46*a23);
  a63=-6.5002611505432138e-04;
  a18=(a63*a18);
  a23=(a23+a18);
  a18=-1.2330556900883628e-03;
  a34=(a18*a34);
  a23=(a23+a34);
  a34=-2.5657898511273188e-04;
  a10=(a34*a10);
  a42=-3.1476678276499748e-01;
  a5=(a42*a5);
  a10=(a10+a5);
  a5=-2.6344970742639309e-04;
  a11=(a5*a11);
  a10=(a10+a11);
  a11=5.6969956386747022e-05;
  a4=(a11*a4);
  a62=-2.6344987974043471e-04;
  a3=(a62*a3);
  a4=(a4+a3);
  a3=-4.3805614316485942e-31;
  a4=(a4+a3);
  a3=1.1531650953807166e-15;
  a4=(a4+a3);
  a10=(a10+a4);
  a23=(a23+a10);
  a33=(a33+a23);
  a45=(a45+a33);
  a57=(a57+a45);
  a68=(a68+a57);
  a76=(a76+a68);
  if (res[0]!=0) res[0][12]=a76;
  a92=(a77*a92);
  a89=(a93*a89);
  a92=(a92+a89);
  a89=(a69*a64);
  a92=(a92+a89);
  a64=(a67*a64);
  a86=(a54*a86);
  a90=(a72*a90);
  a86=(a86+a90);
  a91=(a52*a91);
  a86=(a86+a91);
  a83=(a70*a83);
  a87=(a71*a87);
  a83=(a83+a87);
  a88=(a40*a88);
  a83=(a83+a88);
  a80=(a58*a80);
  a84=(a53*a84);
  a80=(a80+a84);
  a85=(a28*a85);
  a80=(a80+a85);
  a78=(a46*a78);
  a81=(a63*a81);
  a78=(a78+a81);
  a82=(a18*a82);
  a78=(a78+a82);
  a66=(a34*a66);
  a79=(a42*a79);
  a66=(a66+a79);
  a61=(a5*a61);
  a66=(a66+a61);
  a65=(a11*a65);
  a73=(a62*a73);
  a65=(a65+a73);
  a73=-6.0110481068699783e-32;
  a65=(a65+a73);
  a73=-2.2535832518381311e-15;
  a65=(a65+a73);
  a66=(a66+a65);
  a78=(a78+a66);
  a80=(a80+a78);
  a83=(a83+a80);
  a86=(a86+a83);
  a64=(a64+a86);
  a92=(a92+a64);
  if (res[0]!=0) res[0][13]=a92;
  a77=(a77*a74);
  a93=(a93*a75);
  a77=(a77+a93);
  a69=(a69*a0);
  a77=(a77+a69);
  a67=(a67*a0);
  a54=(a54*a55);
  a72=(a72*a56);
  a54=(a54+a72);
  a52=(a52*a49);
  a54=(a54+a52);
  a70=(a70*a43);
  a71=(a71*a44);
  a70=(a70+a71);
  a40=(a40*a37);
  a70=(a70+a40);
  a58=(a58*a31);
  a53=(a53*a32);
  a58=(a58+a53);
  a28=(a28*a25);
  a58=(a58+a28);
  a46=(a46*a21);
  a63=(a63*a22);
  a46=(a46+a63);
  a18=(a18*a14);
  a46=(a46+a18);
  a34=(a34*a8);
  a42=(a42*a9);
  a34=(a34+a42);
  a5=(a5*a7);
  a34=(a34+a5);
  a11=(a11*a95);
  a62=(a62*a96);
  a11=(a11+a62);
  a62=6.9172071199538589e-16;
  a11=(a11+a62);
  a62=3.3300000000000068e-01;
  a11=(a11+a62);
  a34=(a34+a11);
  a46=(a46+a34);
  a58=(a58+a46);
  a70=(a70+a58);
  a54=(a54+a70);
  a67=(a67+a54);
  a77=(a77+a67);
  if (res[0]!=0) res[0][14]=a77;
  a77=1.;
  if (res[0]!=0) res[0][15]=a77;
  return 0;
}

CASADI_SYMBOL_EXPORT int fkpanda_hand_tcp(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int fkpanda_hand_tcp_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int fkpanda_hand_tcp_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fkpanda_hand_tcp_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int fkpanda_hand_tcp_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fkpanda_hand_tcp_release(int mem) {
}

CASADI_SYMBOL_EXPORT void fkpanda_hand_tcp_incref(void) {
}

CASADI_SYMBOL_EXPORT void fkpanda_hand_tcp_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int fkpanda_hand_tcp_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int fkpanda_hand_tcp_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real fkpanda_hand_tcp_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fkpanda_hand_tcp_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fkpanda_hand_tcp_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fkpanda_hand_tcp_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fkpanda_hand_tcp_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int fkpanda_hand_tcp_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int fkpanda_hand_tcp_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
